#!/usr/bin/env node
/**
 * `pnpm glyphs` — regenerate the Icon glyph registry from the committed artwork.
 *
 * SOURCE OF TRUTH is `src/components/Icon/glyphs/*.svg`, one file per glyph. Figma is UPSTREAM of
 * that directory, not the source: artwork is transcribed in, the same way token values are
 * transcribed into DTCG JSON under ADR 0002. Nothing here reads Figma, so this runs on a fresh
 * clone with no network and no plugin.
 *
 * WHAT IT ENFORCES, and why each one is a failure rather than a note:
 *
 *   monochrome   a glyph may paint only with `fill="currentColor"`. This is the mechanized half
 *                of ADR 0004 — an imported glyph that kept its exported hex would silently stop
 *                inheriting colour from where it is placed, and nothing else in the repo would
 *                notice, because a coloured icon renders perfectly well.
 *   one canvas   viewBox must be exactly `0 0 24 24`. A glyph on a different canvas renders at
 *                the wrong optical size inside a box sized by the `size` axis, with no error.
 *   one path     exactly one <path>, no <g>, no stroke. The set was measured to be uniformly
 *                single-path (docs/research/0001-icon-set-audit.md); anything else means an
 *                asset arrived by a route this generator was not built for.
 *   naming       kebab-case, per .ai/maps/prop-map.md §2 and ADR 0005.
 *
 * `--check` asserts the committed registry byte-matches a fresh run. Without it the registry is
 * enforced on whichever machine happens to run `pnpm glyphs`, which is the failure mode the root
 * CLAUDE.md calls out by name.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { COMPONENTS_DIR, byCodePoint } from './lib.mjs';

const check = process.argv.includes('--check');

const GLYPH_DIR = join(COMPONENTS_DIR, 'Icon/glyphs');
const OUT = join(COMPONENTS_DIR, 'Icon/glyphs.ts');

const NAME = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const VIEWBOX = /viewBox="0 0 24 24"/;
const PATH_D = /<path\b[^>]*\bd="([^"]+)"/g;

function main() {
  if (!existsSync(GLYPH_DIR)) {
    console.error(`no glyph directory at ${GLYPH_DIR}`);
    process.exit(1);
  }

  const files = readdirSync(GLYPH_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort(byCodePoint); // fixed comparator, never localeCompare — output must be machine-stable

  const problems = [];
  const glyphs = [];

  for (const file of files) {
    const name = file.replace(/\.svg$/, '');
    const src = readFileSync(join(GLYPH_DIR, file), 'utf8');
    const where = `glyphs/${file}`;

    if (!NAME.test(name)) {
      problems.push(`${where}: "${name}" is not kebab-case.`);
      continue;
    }
    if (!VIEWBOX.test(src)) {
      problems.push(`${where}: viewBox must be exactly "0 0 24 24".`);
      continue;
    }

    const fills = [...src.matchAll(/fill="([^"]*)"/g)].map((m) => m[1]);
    const offending = fills.filter((f) => f !== 'currentColor');
    if (offending.length) {
      problems.push(
        `${where}: fill must be "currentColor", found ${offending.map((f) => `"${f}"`).join(', ')}. ` +
          `A glyph does not carry its own colour — see ADR 0004.`,
      );
      continue;
    }
    if (
      /<(g|stroke|circle|rect|ellipse|polygon|polyline|line)\b/.test(src) ||
      /stroke=/.test(src)
    ) {
      problems.push(`${where}: expected a single <path> and nothing else.`);
      continue;
    }

    const ds = [...src.matchAll(PATH_D)].map((m) => m[1]);
    if (ds.length !== 1) {
      problems.push(`${where}: expected exactly one <path>, found ${ds.length}.`);
      continue;
    }

    glyphs.push([name, ds[0]]);
  }

  if (problems.length) {
    console.error(`glyphs: ${problems.length} problem(s):\n`);
    for (const p of problems.sort(byCodePoint)) console.error(`  ${p}`);
    process.exit(1);
  }

  const text = render(glyphs);

  if (check) {
    const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null;
    if (current !== text) {
      console.error(
        'glyphs:check failed — glyphs.ts is not what the committed artwork produces.\n' +
          'Run `pnpm glyphs` and commit the result. Never hand-edit the generated file.',
      );
      process.exit(1);
    }
    console.log(`glyphs:check OK — ${glyphs.length} glyphs, registry is current.`);
    return;
  }

  writeFileSync(OUT, text);
  console.log(`glyphs: wrote ${glyphs.length} glyphs to ${OUT}.`);
}

function render(glyphs) {
  const L = [];
  L.push('// GENERATED by packages/react/scripts/build-glyphs.mjs — DO NOT EDIT BY HAND.');
  L.push('// Regenerate with `pnpm glyphs`. `pnpm glyphs:check` asserts this file byte-matches');
  L.push('// the artwork in ./glyphs/, so an edit here is discarded and reddens the build.');
  L.push('//');
  L.push('// The artwork is the source; this file is a transcription of it. To add, remove or');
  L.push('// redraw a glyph, change the SVG in ./glyphs/ and regenerate.');
  L.push('');
  L.push('/** Every glyph in the set, as its single path. All are drawn on a 24x24 canvas. */');
  L.push('export const glyphs = {');
  for (const [name, d] of glyphs) L.push(`  '${name}': '${d}',`);
  L.push('} as const;');
  L.push('');
  L.push('/** The name of a glyph in the set. */');
  L.push('export type GlyphName = keyof typeof glyphs;');
  L.push('');
  L.push('/** Every glyph name, in code-point order. Useful for building a picker. */');
  L.push('export const glyphNames = Object.keys(glyphs) as GlyphName[];');
  L.push('');
  return L.join('\n');
}

main();
